server:
  port: 8080
spring:
  #通用的数据源配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/softEngineer?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: Lgl13986678376
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none